name: Size Label
on: pull_request
jobs:
  size-label:
    runs-on: ubuntu-latest
    # Do not run on dependabot PRs
    if: github.actor != 'dependabot[bot]'
    steps:
      - name: size-label
        uses: "pascalgn/size-label-action@v0.5.5"
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"